### PR TITLE
Two-Sum O(n) solution without needing to previously sort array

### PR DESCRIPTION
**Pull request by D-Speiser**

### CODE REVIEW

**Comment by hollance** [comment]
Hey, thanks for that! I have a request to make, though: instead of replacing the existing solution, could you simply add this new one as an alternative? It's nicer for readers to see two solutions.

Can you also add a description of your solution to the README, which an explanation of the upsides and downsides compared to the other algorithm? That would be awesome, thanks!

**Comment by D-Speiser** [comment]
Sure, not a problem. I'll push changes later tonight or tomorrow.

**Comment by D-Speiser** [comment]
pushed changes you've asked for @hollance

**Comment by hollance** [comment]
Just a quick update: I edited your description slightly to fit in better with the existing text.

I also made a small change to the code. Instead of `for i in 0 ... a.count - 1`, I used `for i in 0 ..< a.count`. It's debatable which one is "better", but I prefer the latter.

Thanks again for this!

**Pull request merged**
