### PR TITLE
Add singly linked list

### PR DESCRIPTION
**Pull request by macbellingrath**

### CODE REVIEW

**Comment by hollance** [comment]
Hey Mac, thanks for the contribution.

Could you also write up a description of how this works? Having code is great but having an explanation is even better! :-)

**Comment by macbellingrath** [comment]
Yes, writing it up now.

**Comment by hollance** [comment]
Awesome, thanks. I'll tweak the naming of things a little but other than that it looks great. :-)

**Comment by hollance** [comment]
Just a bit of follow-up: 

I was writing an article on doubly linked lists and decided to fold the singly linked list into this and just have one article describing both.

I also noticed your singly linked list code was very similar to the one from Wayne Bishop's book on algorithms. I'm not a big fan of that code, and as you can see my version of LinkedList takes a bit of a different approach in several places.

Thanks anyway for your work, and please don't let this stop you from contributing other algorithms. :-)

**Pull request merged**
