### PR TITLE
Add B-tree paragraph placeholder

### PR DESCRIPTION
**Pull request by Hout**
Title says it all. Fun project to work on.

### CODE REVIEW

**Comment by hollance** [comment]
I merged it so that your "claim is staked". ;-)

**Comment by hollance** [comment]
@Hout What is the status on this? Is it still something you're willing to work on?

**Comment by Hout** [comment]
Yep! However progress is slow I am afraid.
Do you expect pull requests for intermediate results?

**Comment by hollance** [comment]
Take your time. :-) Feel free to make pull requests but it's not a requirement.

**Pull request merged**
