### PR TITLE
Graph Implementation

### PR DESCRIPTION
**Pull request by donald-pinckney**
Working on the plain graph code, not yet close to done.  Currently I am focusing on representing directed, weighted graphs using adjacency lists.  Feedback is welcome!

### CODE REVIEW

**Comment by hollance** [comment]
Great! Graphs are fun. :-)

**Comment by hollance** [comment]
@donald-pinckney How are you getting along with the description? Just checking in... ;-)

**Comment by donald-pinckney** [comment]
@hollance Sorry, midterms hit, and I kinda lost track of things!  I just committed some initial content for the description.  I know its not complete, as I at least want to add some images in.  Would you mind looking over it, and suggesting any other changes or additions?  Thanks.

**Comment by hollance** [comment]
Looks good! But yeah, it definitely needs some images. Someone who is new to graphs may have trouble visualizing what they look like otherwise.

Maybe you can give a few more examples of why someone would use a graph (and maybe note that a tree is a simplified graph).

**Comment by hollance** [comment]
OK, I'm merging this and will do a quick edit.

**Comment by donald-pinckney** [comment]
Cool, thanks. Sorry I didn't keep up with the writing.

**Comment by hollance** [comment]
No worries. :-)

**Comment by donald-pinckney** [comment]
@hollance Hey, I just looked at the current explanation for graphs.  I just want to say, great work.  You are very good at writing in a way that makes it easy for readers to relate.  You humble me as I realize how much I can improve my writing skills.

**Comment by hollance** [comment]
@donald-pinckney Thanks. Consider contributing to this repo as an opportunity to do so. :-) There's still quite a bit of stuff that needs work.

Usually when I read through an explanation and think to myself, "I wonder why that is true / I don't understand this / But what about... ?" then I add some clarifying text. Feel free to do the same!

**Pull request merged**
