### PR TITLE
Add Bloom Filter Implementation & Description

### PR DESCRIPTION
**Pull request by Jamil**
Just worked on an implementation of a Bloom Filter; the API could be extended, but it's a simple and concise working implementation.

The unit tests ensure that the Bloom Filter works with single or multiple hash functions, with different set sizes, and with different numbers of elements inserted. Of course it could be extended later too :)

### CODE REVIEW

**Comment by hollance** [comment]
Hey wow, this looks very nice Jamil!

**Comment by hollance** [comment]
FYI: I expanded the text a bit and tweaked the code style. Thanks again, this is a really cool data structure. :-)

**Comment by Jamil** [comment]
No problem! It's one of my favorite data structures.

Thanks for the fixes -- the description's a lot more comprehensive and readable now. I did it in a bit of a rush :)

**Comment by hollance** [comment]
I wanted to write a separate thing about hashing. Not hash tables (already have that) but just the topic of hashing in general. Since you already wrote a little about that for the Bloom Filter, I thought maybe you'd feel like writing something about hashing in general? (Just in case you're looking for something to do. ;-) )

**Pull request merged**
