### PR TITLE
Fixed AVL Tree bug

### PR DESCRIPTION
**Pull request by prankymat**
This is a pull request in response to #61 

- Tree rotation was replaced by updating links of the tree structure
    + Keep track of the height of each node
    + Determine if the node needs to be rotated by comparing the left right factor
- Delete node will recurse until reaches a leave node, otherwise replace target by a replacement (successor)
- Removed irrelevant test cases

### CODE REVIEW

**Comment by hollance** [comment]
Thanks for fixing the bug, but could you use the original indentation settings? Now there's a ton of code that's listed as changed when it's just the indentation that is different. This makes it hard to see the actual changes. ;-)

**Comment by prankymat** [comment]
@hollance Sure will do! Will push changes here

**Comment by prankymat** [comment]
nvm! Found the coding style here! https://github.com/raywenderlich/swift-style-guide Sorry for my silly question!

**Comment by prankymat** [comment]
I'm closing this pull request as I've created another to fix the indentations issues in this pull request. Please proceed to #81

**Pull request closed without merging**
