### PR TITLE
READY TO REVIEW: Bucket Sort

### PR DESCRIPTION
**Pull request by barbaramartina**
I'll be working on this sorting algorithm.

### CODE REVIEW

**Comment by barbaramartina** [comment]
Hi @hollance just an update:  I have added changes but I'm still not finished here. I need to prepare the  documention.

**Comment by hollance** [comment]
Sure, just let me know when it's done. :-)

**Comment by barbaramartina** [comment]
@hollance I'm done with this, it's ready to review. I'll go back to see your comments next week, Thursday / Friday. thanks!

**Comment by hollance** [comment]
Cool, I'll look at it soon. :-)

**Comment by hollance** [comment]
I had a quick look and I think the explanation needs some work. 

It looks like you took some things from Wikipedia. It would be better to describe these things in your own words (otherwise people might just as well check out Wikipedia). 

I always like to work through an example step-by-step. That lets you describe the algorithm but also makes it easy for readers to follow along.

**Comment by barbaramartina** [comment]
Hi Hollance, I like reusing knowledge and Wikipedia is a good source of
knowledge to reuse, their graphics and explanations are very clear. I could
add some more examples, step by steps, this could help to explain this
specific implementation. But I really don't see the necessity of
re-explaining the basic algorithm in other words.

Barbara

*Skype*: barbararodeker
*Mobile*: +49 1745414522
*Phone*: +49  030 60400089
*LinkedIn*: ar.linkedin.com/in/barbararodeker/en

**Comment by hollance** [comment]
"Re-explaining the algorithm in other words" is pretty much the idea behind this project. ;-) 

I often don't find the Wikipedia explanations very clear and so I try to do a better job (but one that is probably less academically rigorous). [And to be honest, writing down the explanation in my own words, and including step-by-step examples makes *me* understand the algorithm better too.]

It's OK if you want to leave the explanation in its current state, but then I'll probably end up editing it quite a bit (which I do with most pull requests anyway). It may be a while before I get around to that.

**Comment by barbaramartina** [comment]
Hi Hollance, I'm coming back to this.  
Thanks for explaining, I see your point now, and I see the advantage of explaining it not so academically, I'll be following the merge sort example that you mentioned in the collaboration section to complete the docs, of course feel free to re-edit anything.

**Comment by hollance** [comment]
Awesome, thanks. I'll look at it soon! :-)

**Pull request merged**
