### PR TITLE
Added Heap

### PR DESCRIPTION
**Pull request by kevinrandrup**
I created a Heap protocol and implemented a MaxHeap. I also included some basic tests. They aren’t exhaustive by any means but I used them to verify everything is working correctly.

### CODE REVIEW

**Comment by kevinrandrup** [comment]
I'll be happy to contribute a written description and a PriorityQueue implementation if everything looks good with this implementation.

**Comment by hollance** [comment]
Looks very good!

I'd really appreciate it if you could add a written explanation. :-) (Don't forget to include your name in the description, so you get some credit for your work.)

**Comment by samirGuerdah** [comment]
@kevinrandrup How you are running the tests ?

**Comment by kevinrandrup** [comment]
@samirGuerdah It doesn't supposed XCTest. I just copy pasted the files into an Xcode project.

**Comment by hollance** [comment]
Awesome, I've merged it and made a few small changes. Most importantly, I created an Xcode project for the unit tests. Thanks again, Kevin!

**Pull request merged**
