### PR TITLE
Claim Adjacency List and Radix Tree

### PR DESCRIPTION
**Pull request by scalls**
Hi,

I am working in the group project that JFTung mentioned in pull request #102. I had not created the directories and linked them to the master README, so my "claims" were not included. I created a directory for both Adjacency List and Radix Tree, linked them to the master README, and created a placeholder README file in those directories.

### CODE REVIEW

**Comment by hollance** [comment]
I know what an Adjacency List is in the context of a graph, but I didn't know about a separate data structure called ad adjacency list. What does this do?

**Comment by scalls** [comment]
I think that is a typo, I'm not sure what an ad adjacency list is either.

**Comment by hollance** [comment]
Ah ok. Note that we already have that inside Graph. Improvements are always welcome of course. :-)

**Comment by scalls** [comment]
Hi,

Just wanted to check in again. I have scrapped my work on the Adjacency List data structure and decided to focus my efforts on creating the Radix Tree. I have implemented most functionality and have updated the README significantly.

**Comment by hollance** [comment]
Cool. Make sure you give credit to the creator of the image, per the license.

**Comment by hollance** [comment]
Is this done now? If yes, then I'll merge it and do my customary edit (where necessary).

**Comment by scalls** [comment]
Yes, go ahead and merge

**Comment by hollance** [comment]
OK, I've made some tweaks.

Some remarks:

- The code seems quite complex. It would be useful if you explain how the important operations work in the README.
- I removed some stuff from the README. It read more like an API reference than an explanation of how the algorithm actually works, but explaining how it works is the purpose of this project.
- We're not using Swift 3 yet. ;-) I guess you're on Linux so you have no other choice but I had to change the code back to Swift 2.x for now.
- I added your name to the README.

**Pull request merged**
