### PR TITLE
Using isEmpty instead of count for the array pop method

### PR DESCRIPTION
**Pull request by darren102**
Per discussion previously using `isEmpty` on the array instead of `count`

### CODE REVIEW

**Comment by kevinrandrup** [comment]
That guard is really confusing. It reads like "if array is not 'not empty' then return nil. `isEmtpy` is better than `count == 1` but I think guard should be reserved for failing to bind an optional value at the beginning of the function.

**Comment by hollance** [comment]
I like the use of `isEmpty`, but agree that `guard` makes it more confusing than it needs to be. So I'll close this PR and make those changes.

**Comment by micpringle** [comment]
Why not simply...

```swift
if array.isEmpty { return nil }
return array.removeLast()
```

I don't think an `else` is necessary here.

**Comment by hollance** [comment]
The `else` is not strictly necessary, but in my opinion it does clarify the flow of what's going on.

**Comment by micpringle** [comment]
In that case, what about ...

```swift
return array.isEmpty ? nil : array.removeLast()
```

:smile:

**Comment by hollance** [comment]
Perfectly fine, but since the goal of this project is to teach algorithms I'd prefer to stick with an simple `if-else` since everyone understands that.

**Pull request closed without merging**
