### PR TITLE
Binary Tree

### PR DESCRIPTION
**Pull request by mitghi**
I added Binary Tree implementation. It uses Generics and can be used right-away as key-value data structure.

Example:

    //                   key, value ( payload )

    var mbt = BinaryTree<Int,String>()

    for i in [10,8,9,24,22,26]{
        mbt[i] = "\(i)_test"
    }

    mbt.delete(10)
    print("\(mbt.root!.rightchild!.rightchild!.key) -> \(mbt.root!.rightchild!.rightchild!.value)")
    mbt.delete(26)
    print(mbt.root!.rightchild!.rightchild?.value)

### CODE REVIEW

**Comment by hollance** [comment]
Thanks! Someone else is already providing a binary search tree but their implementation uses an enum and doesn't have all your functionality.

Once their version is added to the repo, could you add your code in that same folder? And also write an explanation of how your version works? That way readers can compare the different approaches, that would be great.

**Comment by mitghi** [comment]
Sure, I will do that. Should i close this pull request ?

**Comment by hollance** [comment]
Yeah, I'll close it.

**Comment by mitghi** [comment]
Please provide some additional information about the folder structure ? How should i put it there ? Should i add another readme ?

**Comment by hollance** [comment]
Ideally, I'd like to have all the explanations in a single README file. The existing version uses an enum. So you'd add a new section to the README explaining how your version is different, and explain any additional functionality that you added.

There is a small problem: the other binary search tree README isn't finished yet. So it's probably a bad idea to start messing with those files right now.

Here's an idea: Create a folder "Binary Search Tree 2" (in the top-level directory) and add your stuff in there. Then at some point I will merge the READMEs.

How does that sound?

**Comment by mitghi** [comment]
Thanks a lot for the info. That sounds great, but i just rewrote it as an AVL tree. You can have look at it (here)[https://github.com/mitghi/swift-algorithm-club/tree/master/AVL%20Tree]. I am completing the README file and as soon as its finished, i make a pull request.

Thankd

**Pull request closed without merging**
