### PR TITLE
Shunting yard algorithm

### PR DESCRIPTION
**Pull request by aliHafizji**
Details on the algorithm are here: https://en.wikipedia.org/wiki/Shunting-yard_algorithm

Todo list:

- [x] Make the code readable especially they way expressions are created
- [x] Add details about the algorithm

### CODE REVIEW

**Comment by hollance** [comment]
Cool, I had not heard of this.

**Comment by aliHafizji** [comment]
@hollance This is ready for review :eyes: 
Let me know what you think.

**Comment by hollance** [comment]
I think it's cool. :-D

**Comment by hollance** [comment]
I made some tweaks to the text and the code, but nothing major. I also removed the Stack.swift file because people can find that in the Stack/ folder (plus it's already in the playground).

**Pull request merged**
