### PR TITLE
Union-Find data structure implementation

### PR DESCRIPTION
**Pull request by goingreen**
I have only to write an explanation. I think it will be ready tomorrow.

### CODE REVIEW

**Comment by hollance** [comment]
What does the DS stand for?

**Comment by goingreen** [comment]
It's abbreviation for DataStructure. Do you think that it's redundant?

**Comment by hollance** [comment]
Yeah, I don't think "DS" adds anything so I would leave it out.

Have you considered making it a `struct` instead of a `class`? In Swift most collection types are structs.

**Comment by goingreen** [comment]
I haven't thought of it as collection type. But I've taken into consideration your сomment and now changed my mind so I suppose to make it a `struct`.

**Comment by goingreen** [comment]
I want to refactor this very unsafe line of code `let indexOfElement = index[element]!`. But I don't know what would be better: calling `fatalError()` or throwing exception? @hollance What are your thoughts?

**Comment by hollance** [comment]
I would solve this by returning nil if the element cannot be found:

```
public mutating func findSetOfElement(element: T) -> Int? {
  if let indexOfElement = index[element] {
    return findSetByIndexOfElement(indexOfElement)
  } else {
    return nil
  }
}
```

**Comment by hollance** [comment]
By the way, can you rename the directory to `Union-Find`?

**Comment by goingreen** [comment]
Also I'm thinking about helper method like
```swift
public mutating func isInTheSameSet(firstElement: T, secondElement: T) -> Bool {
  if let firstSet = findSetOfElement(firstElement), secondSet = findSetOfElement(secondElement) {
    return firstSet == secondSet
  } else {
    return false
  }
}
```

**Comment by hollance** [comment]
I have some suggestions for name changes. Not that your names are bad, but they could be simplified a little.

- `isInTheSameSet()` could just be `inSameSet()`
- `findSetOfElement()` could be `setOfElement()` or even just `setOf()`
- `addSetWithElement()` could just be `add()`
- `unionSetsWithElement(andSecondElement:)` could be `unionSetsContaining(and:)`

I also notice you used `( )` with some if-statements and even some semicolons! :scream: ;-)

**Comment by goingreen** [comment]
I still write some ObjC but I'm honestly trying to get rid of this habit :flushed:
I have some doubts about renaming `addSetWithElement()` to `add()` because it becomes a bit not clear what we actually add. In my opinion, the best solution is `addSetWith()`

**Comment by hollance** [comment]
The idea is that each element you add is given its own set containing just that element, right? I agree that just `add()` may not make that very clear.

**Comment by goingreen** [comment]
I think I've done. Do you have any remarks?

**Comment by hollance** [comment]
Looking good. :-) I'll probably merge it tomorrow.

**Comment by hollance** [comment]
Very nice! I tweaked the description a little for grammar etc.

**Comment by goingreen** [comment]
Thank you for your work. Now it looks much better!

**Pull request merged**
