### PR TITLE
Implement Longest Common Subsequence

### PR DESCRIPTION
**Pull request by pedrovereza**
Adds Longest Common Subsequence algorithm. Still need to work on the README.

### CODE REVIEW

**Comment by hollance** [comment]
Cool, this was definitely on my list.

**Comment by pedrovereza** [comment]
Think I have a first complete version of it. 
Let me know what you think :wink:

**Comment by hollance** [comment]
Looking good! Thanks. :-)

**Comment by hollance** [comment]
I've tweaked the code a little and made some additions and modifications to the text. Really cool algorithm! Thanks again! :-)

**Pull request merged**
